config/routes.rb
Voucherific::Application.routes.draw do
  get "home/index"

  get "home/about"

  resources :vouchers

  root :to => 'home#index'

end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  attr_accessible :description, :expires_on, :from_email, :from_name, :passcode, :title, :to_email, :to_name, :used
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController
  # GET /vouchers
  # GET /vouchers.json
  def index
    @vouchers = Voucher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vouchers }
    end
  end

  # GET /vouchers/1
  # GET /vouchers/1.json
  def show
    @voucher = Voucher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @voucher }
    end
  end

  #GET /vouchers/use/1
  def use
    @voucher = Voucher.find(param[:id])
    @voucher.used = true
    @voucher.save
    VocuherMailer.use_voucher(@voucher).deliver
    format.html { redirect_to @voucher, notice: 'Voucher has been used.' }
  end

  # GET /vouchers/new
  # GET /vouchers/new.json
  def new
    @voucher = Voucher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @voucher }
    end
  end

  # GET /vouchers/1/edit
  def edit
    @voucher = Voucher.find(params[:id])
  end

  # POST /vouchers
  # POST /vouchers.json
  def create
    @voucher = Voucher.new(params[:voucher])

    respond_to do |format|
      if @voucher.save
        VoucherMailer.send_voucher(@voucher).deliver
        format.html { redirect_to @voucher, notice: 'Voucher was successfully created.' }
        format.json { render json: @voucher, status: :created, location: @voucher }
      else
        format.html { render action: "new" }
        format.json { render json: @voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vouchers/1
  # PUT /vouchers/1.json
  def update
    @voucher = Voucher.find(params[:id])

    respond_to do |format|
      if @voucher.update_attributes(params[:voucher])
        format.html { redirect_to @voucher, notice: 'Voucher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vouchers/1
  # DELETE /vouchers/1.json
  def destroy
    @voucher = Voucher.find(params[:id])
    @voucher.destroy

    respond_to do |format|
      format.html { redirect_to vouchers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<div class="hero-unit">
	<h1>Couponific</h1>
	<p>Save a tree and your money. Create and Send a coupon to your loved ones.</p>
	<a href="#" class="btn btn-primary btn-large">Create and Send a Coupon</a>
		<a href="#" class="btn btn-info btn-large">See some Examples</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Couponific" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="">Couponific</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Create", "/path1"  %></li>
              <li><%= link_to "Examples", "" %></li>
              <li><%= link_to "About", "/path2"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; <a href="http://aliirz.com">Ali Raza</a> 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/vouchers/_form.html.erb
<%= form_for @voucher, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <label class="control-label">Title</label>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field', :placeholder => 'e.g One Free DVD' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area', :placeholder => 'e.g I will buy you one DVD of your choice' %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Your Name</label>
    <div class="controls">
      <%= f.text_field :from_name, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label">Your Email</label>
    <div class="controls">
      <%= f.text_field :from_email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Their Name</label>
    <div class="controls">
      <%= f.text_field :to_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Their Email</label>
    <div class="controls">
      <%= f.text_field :to_email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :expires_on, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :expires_on, :class => 'date_select' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary btn-large' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                vouchers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/vouchers/edit.html.erb
<%- model_class = Voucher -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vouchers/index.html.erb
<%- model_class = Voucher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:from_name) %></th>
      <th><%= model_class.human_attribute_name(:to_name) %></th>
      <th><%= model_class.human_attribute_name(:from_email) %></th>
      <th><%= model_class.human_attribute_name(:to_email) %></th>
      <th><%= model_class.human_attribute_name(:expires_on) %></th>
      <th><%= model_class.human_attribute_name(:passcode) %></th>
      <th><%= model_class.human_attribute_name(:used) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @vouchers.each do |voucher| %>
      <tr>
        <td><%= link_to voucher.id, voucher_path(voucher) %></td>
        <td><%= voucher.title %></td>
        <td><%= voucher.description %></td>
        <td><%= voucher.from_name %></td>
        <td><%= voucher.to_name %></td>
        <td><%= voucher.from_email %></td>
        <td><%= voucher.to_email %></td>
        <td><%= voucher.expires_on %></td>
        <td><%= voucher.passcode %></td>
        <td><%= voucher.used %></td>
        <td><%=l voucher.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_voucher_path(voucher), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      voucher_path(voucher),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_voucher_path,
            :class => 'btn btn-primary' %>

app/views/vouchers/new.html.erb
<%- model_class = Voucher -%>
<div class="page-header">
  <h1>Create and Send a Coupon</h1>
</div>
<div class="row-fluid">
	<div class="span9">
		<%= render :partial => 'form' %>
	</div>
	<div class="span3">
		<div class="alert alert-info">
			<p>
				Create and Send a Coupon to your friend. Once they use the voucher you will receive an email. Then it will be time to be true to your word. 
			</p>
		</div>

</div>

app/views/vouchers/show.html.erb
<div class="hero-unit">
  <div class="alert alert-success">
    <h1><%= @voucher.title %></h1>
    <h2><%= @voucher.description %></h2>
    <p> Expires on: <%= @voucher.expires_on %> </p>
    <p> From: <%= @voucher.from_name %> </p>
  </div>
  <a href="" class="btn btn-large btn-success">Use</a>
  <%= link_to "Use Coupon", voucher_path(@voucher,:voucher => {:used => true}),
  :method => :put,
  :confirm => "Are you sure you want to use this coupon?" %>
</div>



<%- model_class = Voucher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @voucher.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @voucher.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:from_name) %>:</strong></dt>
  <dd><%= @voucher.from_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:to_name) %>:</strong></dt>
  <dd><%= @voucher.to_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:from_email) %>:</strong></dt>
  <dd><%= @voucher.from_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:to_email) %>:</strong></dt>
  <dd><%= @voucher.to_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expires_on) %>:</strong></dt>
  <dd><%= @voucher.expires_on %></dd>
  <dt><strong><%= model_class.human_attribute_name(:passcode) %>:</strong></dt>
  <dd><%= @voucher.passcode %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              vouchers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_voucher_path(@voucher), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              voucher_path(@voucher),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>